### ISSUE TITLE
don't generate redundant code

### ISSUE THREAD

**Issue by Morriz** [omar-dulaimi/prisma-yup-generator#4]
## Problem

Hi, all your `objects/*.schema` files contain redundant code. The top definition is always copied to be used in the exported `Yup.object({...`.

## Suggested solution

Just export like this:
```ts
export const UserUpdateInputObject = ...
...
export const UserUpdateInputObjectSchema = Yup.object(UserUpdateInputObject)
```

**Comment by Morriz** [comment]
It would also be really awesome if you could generate indexes so that we can just import like this:
```
import { UserUpdateInputObjectSchema } from `*/gen/schemas`
```

**Comment by omar-dulaimi** [comment]
> ```ts
> export const UserUpdateInputObject = ...
> ...
> export const UserUpdateInputObjectSchema = Yup.object(UserUpdateInputObject)
> ```

This would be really cool if it works and doesn't show any errors. Hopefully it works!
