### ISSUE TITLE
Option to enable force overwrite

### ISSUE THREAD

**Issue by mubaidr** [omar-dulaimi/prisma-yup-generator#8]
## Problem

Generator fails with existing files. 

## Suggested solution

Generator should overwrite generated files or have an option to enable force overwrite.

## Alternatives

none

## Additional context

Just running generator multiple times. 

P.S. Thanks for excellent work, output is clean, up-to standard!

**Comment by omar-dulaimi** [comment]
Hey @mubaidr 

I just tried to re-generate a few times, and it went okay every single time. So maybe you're doing something different on your end?

Please share your generator block in the schema and the tsconfig file.

**Comment by mubaidr** [comment]
I will test again. Check and share my config.
